---
name: cmpsc-300-spring-2021-lab2
break: true
indent: 4
---

# --> check the technical writing
writing/part1.md:
    ConfirmFileExists
    CountFileWords --count 30
    CountMarkdownTags --tag "heading" --count 6 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

writing/part2.md:
    ConfirmFileExists
    CountFileWords --count 30
    CountMarkdownTags --tag "heading" --count 8 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact



# --> check the number of commits beyond a threshold
CountCommits --count 3
